# Generated by Django 5.2 on 2026-05-12 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='departments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='specialities/')),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('education_form', models.CharField(max_length=100)),
                ('budget_places', models.PositiveIntegerField(default=0)),
                ('paid_places', models.PositiveIntegerField(default=0)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employment_rate', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='education.department')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
