# Generated by Django 5.2 on 2026-05-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='specialities/'),
        ),
    ]
