# Generated by Django 5.2 on 2026-05-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_activitylog_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='exam_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='is_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='ranking_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
