# Generated by Django 5.2 on 2026-05-14 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_application_exam_score_application_is_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
